[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcdr-plugin-template"
dynamic = ["version"]
description = "MCDR plugin template repository."
readme = "README.md"
authors = [
    { name = "Mooling0602", email = "clemooling@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mcdreforged>=2.15.7",
    "prompt-toolkit>=3.0.52",
]

[dependency-groups]
dev = ["ruff>=0.15.12", "ty>=0.0.33"]

[tool.hatch.version]
source = "regex"
path = "src/mcdreforged.plugin.json"
pattern = '"version"\s*:\s*"(?P<version>[^"]+)"'

[tool.hatch.build.targets.wheel]
packages = ["src/plugin_id"]
